# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/rubocop-hq/rubocop
    rev: v1.29.1
    hooks:
      - id: rubocop
        name: Check Ruby files with rubocop
        args: [--debug]
        always_run: true
        pass_filenames: false
  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.8.0.4
  #   hooks:
  #     - id: shellcheck
  #       name: Check shell scripts with shellcheck
  #       files: ^.*\.(sh|bash|ksh)$
  #       types: []
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        name: Check YAML syntax with yamllint
        args: [--strict, '.']
        always_run: true
        pass_filenames: false
  - repo: https://github.com/warpnet/salt-lint
    rev: v0.8.0
    hooks:
      - id: salt-lint
        name: Check Salt files using salt-lint
        files: ^.*\.(sls|jinja|j2|tmpl|tst)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
